routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function(){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group([
        'as'      => 'bank.',
        'prefix'  => 'bank'
    ], function () {
        Route::resource('lists', 'BankController');
        Route::resource('trans', 'BankTransController');
        Route::resource('users', 'BankUsersController');
        Route::resource('accounts', 'BankAccountsController');
        Route::resource('logs', 'BankLogController')->only('index', 'show', 'destroy');

        Route::group([
        'as'      => 'users.',
        'prefix'  => 'users/{user}'
        ], function () {
            Route::post('get-bank', 'BankUsersController@get_bank')->name('getBank');
        });
    });
});

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\ModelScopes;

class Bank extends Model
{
    use ModelScopes;

    /* Bank Status */
    const BANK_ST_ACTIVE    = 1;
    const BANK_ST_INACTIVE  = 2;

    /* BCA Full Code */
    const BANK_BCA_CODE = '0140397';
    
    protected $fillable = [
        'full_code',
        'code',
        'rtgs_code',
        'personal_lib',
        'corporate_lib',
        'name',
        'city',
        'status'
    ];
    
    protected $appends = [
        'statusName'
    ];

    public static function lists($attr='name') {
        $lists = Bank::where(['status' => 1])
                    ->orderBy($attr)
                    ->pluck( $attr, 'id' );

        return $lists;
    }

    public static function listStatus(){
        return [
            self::BANK_ST_ACTIVE   => 'Active',
            self::BANK_ST_INACTIVE => 'Inactive',
        ];
    }

    public function getStatusNameAttribute(){
        $status = '';
        switch($this->attributes['status']){
            case self::BANK_ST_ACTIVE:
                $status = 'Active';
                break;
            case self::BANK_ST_INACTIVE :
                $status = 'Inactive';
                break;
        }
        return $status;
    }

    public static function getStatusName($code){
        $status = '';
        switch($code){
            case self::BANK_ST_ACTIVE:
                $status = 'Active';
                break;
            case self::BANK_ST_INACTIVE :
                $status = 'Inactive';
                break;
        }
        return $status;
    }
    
    public static function getBCA()
    {
        $model = self::where(['full_code' => self::BANK_BCA_CODE]);
        return optional($model)->first();
    }
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Bank;
use Session;

class BankController extends Controller
{
    protected $modelName = 'Banks';
    protected $model;
    protected $listStatus;

    function __construct(){
        $this->model        = Bank::modelName();
        $this->listStatus   = Bank::listStatus();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title      = $this->title($this->modelName);
        $modelName  = $this->modelName;
        $model      = $this->model;
        $listStatus = $this->listStatus;
        $models     = Bank::paginate(10);
        return view('bank.lists.index', compact('title', 'models', 'modelName', 'model', 'listStatus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model      = Bank::findOrFail($id);
        $title      = $this->title($this->modelName, 'create a new');
        $modelName  = $this->modelName;
        $listStatus = $this->listStatus;
        $actionForm = (Str::contains($this->currentAction(), ['edit', 'create'])) ? true : false ;
        return view('bank.lists._form', compact('title', 'model', 'modelName', 'listStatus', 'actionForm'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model      = Bank::findOrFail($id);
        $title      = $this->title($this->modelName, 'create a new');
        $modelName  = $this->modelName;
        $listStatus = $this->listStatus;
        $actionForm = (Str::contains($this->currentAction(), ['edit', 'create'])) ? true : false ;
        return view('bank.lists._form', compact('title', 'model', 'modelName', 'listStatus', 'actionForm'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \DB::beginTransaction();
        try {
            $actionName = 'updated';
            $data       = $request->all();
            $model      = Bank::findOrFail($id);

            if ($model->fill($data) && $model->save()) {
                Session::flash('status', 'success');
                Session::flash('head', 'Item '.$actionName.' successfully');
                Session::flash('message', $this->title($this->modelName)." name '".$model->name."' ".$actionName.".");
                \DB::commit();
            } else {
                Session::flash('status', 'error');
                Session::flash('head', 'Item not '.$actionName.' successfully');
                Session::flash('message', $this->title($this->modelName)." name '".$model->name."' not ".$actionName.".");
            }    
        } catch (\Exception $exception) {
            \DB::rollback();
            $errorInfo = $exception->errorInfo;
            dd( $errorInfo );
            Session::flash('status', 'error');
            Session::flash('head', 'Item not '.$actionName.' successfully');
            Session::flash('message', $errorInfo);
        }

        return redirect()->route('bank.lists.edit', $model->getKey());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/bank/trans/_delete.blade.php
{!! Form::open([
    'method'=>'DELETE', 
    'url' => route('bank.trans.destroy', ['id'=>'']),
    'style' => 'display:none', 
    'id'    => 'delete-form']) !!}
{!! Form::close() !!}

@section('css')
    @parent
    <link href="{{ asset('css/sweetalert.css') }}" rel="stylesheet">
@show

@section('scripts')
    @parent
    <script src="{{asset('js/sweetalert.min.js')}}"></script>
    <script>
        $(document).ready(function(){
            $('.btn-delete').click(function () {
                const btn = $(this);
                swal({
                    title: "Are you sure?",
                    text: "Your will not be able to recover {{ $modelName }} '"+btn.data('title')+"'!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel this!",
                    closeOnConfirm: false,
                    closeOnCancel: false 
                }, function (isConfirm) {
                    if (isConfirm) {
                        $('.confirm').prop('disabled', true);
                        const fdelete = $('#delete-form');
                        fdelete.attr('action', fdelete.attr('action')+"/"+btn.data('id')).submit();
                    } else {
                        swal("Cancelled", "{{ $modelName }} data is safe :)", "error");
                    }
                });
            });
        });
    </script>
@show

resources/views/bank/trans/_form.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">{{ $modelName }}</div>

    <div class="card-body">
        @include('layouts.flash-session')

        <div class="form-group">
            <label>Username</label>
            {!! Form::text('username', $model->bank_username, [
                    'class'          =>'form-control bank', 
                    'disabled'       => true,
                ]) 
            !!}
        </div>

        <div class="form-group">
            <label>Account Number</label>
            {!! Form::text('account_number', $model->bank_account_number, [
                    'class'          =>'form-control', 
                    'disabled'       => true,
                ]) 
            !!}
        </div>

        <div class="form-group">
            <label>Event</label>
            {!! Form::text('event', $model->event, [
                    'class'          =>'form-control', 
                    'disabled'       => true,
                ]) 
            !!}
        </div>

        <div class="form-group">
            <label>URL</label>
            {!! Form::text('username', $model->url, [
                    'class'          =>'form-control bank', 
                    'disabled'       => true,
                ]) 
            !!}
        </div>

        <div class="form-group">
            <label>HTTP Code</label>
            {!! Form::text('username', $model->http_code, [
                    'class'          =>'form-control bank', 
                    'disabled'       => true,
                ]) 
            !!}
        </div>

        <div class="form-group">
            <label>Response Code</label>
            {!! Form::text('username', $model->response_code, [
                    'class'          =>'form-control bank', 
                    'disabled'       => true,
                ]) 
            !!}
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea name="description" {{ (!$actionForm) ? 'disabled' : '' }} class="form-control" rows="3">{{ $model->description }}</textarea>
        </div>

        <div class="form-group">
            <label>Status</label>
            {!! Form::select('status', $listStatus, $model->status, [
                    'class'         => 'form-control',
                    'disabled'      => true,
                ]) 
            !!}
        </div>

        <div class="col-sm-6 col-sm-offset-2">
            <a href="{{ route('bank.trans.index') }}" class="btn btn-secondary btn-sm">
                <span class="fa fa-list"></span>
                Return to list
            </a>
            @if ($actionForm)
                <a href="#" class="btn btn-danger btn-sm btn-delete" data-id='{{ $model->getKey() }}' data-title='{{ $model->number }}'>
                    <span class="fa fa-trash"></span>
                    Delete
                </a>
            @endif
        </div>

        @if ($model->exists)
            @include('bank.trans._delete')
        @endif
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            $('select[name=bank_user]').change(function(){
                const data  = {_token: '{{ csrf_token() }}'};
                const bui   = $(this).val();
                const url   = "{{ route('bank.users.getBank', 'userx') }}".replace('userx', bui);
                if(bui != ''){
                    fetch(url, {
                        method: 'POST',
                        headers: {
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify(data)
                    })
                    .catch(res => {
                        $('input[name=bank]').val('Bank not found');
                    })
                    .then(response => response.json())
                    .then(res => {
                        $('input[name=bank]').val(res.name);
                    });
                }else{
                    $('input[name=bank]').val('');
                }
            });
        });
</script>
@endsection

resources/views/bank/trans/index.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        {{ $modelName }}
    </div>

    <div class="card-body">
        @include('layouts.flash-session')

        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
                <th class="">Transaction ID</th>
                <th class="">Date</th>
                <th class="">Account Number</th>
                <th class="">Account Name</th>
                <th class="">Description</th>
                <th class="">Debit</th>
                <th class="">Credit</th>
                <th class="text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
                @if ($models->count() == 0)
                    <tr>
                        <td colspan="8" class="text-center">No available {{ $title }}</td>
                    </tr>    
                @else
                    @foreach ($models as $model)
                        <tr>
                            <td>
                                {{ $model->trans_id }}
                            </td>
                            <td>
                                {{ $model->created_at->format('D, d-m-Y h:i') }}
                            </td>
                            <td>
                                {{ $model->bankAccount->number }}
                            </td>
                            <td>
                                {{ $model->bankAccount->name }}
                            </td>
                            <td>
                                {{ $model->description }}
                            </td>
                            <td class="text-right">
                                {!! ($model->type == $model::BANK_TRANS_TY_DB) ? $model->amountFormat : '0' !!}
                            </td>
                            <td class="text-right">
                                {!! ($model->type == $model::BANK_TRANS_TY_CR) ? $model->amountFormat : '0' !!}
                            </td>
                            <td>
                                {{-- <a href="{{route('bank.trans.show', $model->getKey())}}" class="btn btn-primary btn-sm"><em class="fa fa-folder"></em> View </a> --}}
                                <a href="#" class="btn btn-danger btn-sm btn-delete" data-id='{{ $model->getKey() }}' data-title='{{ $model->trans_id }}'><em class="fa fa-trash"></em> Delete </a>
                            </td>
                        </tr>
                    @endforeach
                @endif
          </tbody>
        </table>
        {{ $models->onEachSide(1)->links() }}
    </div>
</div>
@include('bank.trans._delete')
@endsection