routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function(){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::group([
        'as'      => 'bank.',
        'prefix'  => 'bank'
    ], function () {
        Route::resource('lists', 'BankController');
        Route::resource('trans', 'BankTransController');
        Route::resource('users', 'BankUsersController');
        Route::resource('accounts', 'BankAccountsController');
        Route::resource('logs', 'BankLogController')->only('index', 'show', 'destroy');

        Route::group([
        'as'      => 'users.',
        'prefix'  => 'users/{user}'
        ], function () {
            Route::post('get-bank', 'BankUsersController@get_bank')->name('getBank');
        });
    });
});

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\ModelScopes;

class Bank extends Model
{
    use ModelScopes;

    /* Bank Status */
    const BANK_ST_ACTIVE    = 1;
    const BANK_ST_INACTIVE  = 2;

    /* BCA Full Code */
    const BANK_BCA_CODE = '0140397';
    
    protected $fillable = [
        'full_code',
        'code',
        'rtgs_code',
        'personal_lib',
        'corporate_lib',
        'name',
        'city',
        'status'
    ];
    
    protected $appends = [
        'statusName'
    ];

    public static function lists($attr='name') {
        $lists = Bank::where(['status' => 1])
                    ->orderBy($attr)
                    ->pluck( $attr, 'id' );

        return $lists;
    }

    public static function listStatus(){
        return [
            self::BANK_ST_ACTIVE   => 'Active',
            self::BANK_ST_INACTIVE => 'Inactive',
        ];
    }

    public function getStatusNameAttribute(){
        $status = '';
        switch($this->attributes['status']){
            case self::BANK_ST_ACTIVE:
                $status = 'Active';
                break;
            case self::BANK_ST_INACTIVE :
                $status = 'Inactive';
                break;
        }
        return $status;
    }

    public static function getStatusName($code){
        $status = '';
        switch($code){
            case self::BANK_ST_ACTIVE:
                $status = 'Active';
                break;
            case self::BANK_ST_INACTIVE :
                $status = 'Inactive';
                break;
        }
        return $status;
    }
    
    public static function getBCA()
    {
        $model = self::where(['full_code' => self::BANK_BCA_CODE]);
        return optional($model)->first();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Bank;
use Session;

class BankController extends Controller
{
    protected $modelName = 'Banks';
    protected $model;
    protected $listStatus;

    function __construct(){
        $this->model        = Bank::modelName();
        $this->listStatus   = Bank::listStatus();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title      = $this->title($this->modelName);
        $modelName  = $this->modelName;
        $model      = $this->model;
        $listStatus = $this->listStatus;
        $models     = Bank::paginate(10);
        return view('bank.lists.index', compact('title', 'models', 'modelName', 'model', 'listStatus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model      = Bank::findOrFail($id);
        $title      = $this->title($this->modelName, 'create a new');
        $modelName  = $this->modelName;
        $listStatus = $this->listStatus;
        $actionForm = (Str::contains($this->currentAction(), ['edit', 'create'])) ? true : false ;
        return view('bank.lists._form', compact('title', 'model', 'modelName', 'listStatus', 'actionForm'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model      = Bank::findOrFail($id);
        $title      = $this->title($this->modelName, 'create a new');
        $modelName  = $this->modelName;
        $listStatus = $this->listStatus;
        $actionForm = (Str::contains($this->currentAction(), ['edit', 'create'])) ? true : false ;
        return view('bank.lists._form', compact('title', 'model', 'modelName', 'listStatus', 'actionForm'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \DB::beginTransaction();
        try {
            $actionName = 'updated';
            $data       = $request->all();
            $model      = Bank::findOrFail($id);

            if ($model->fill($data) && $model->save()) {
                Session::flash('status', 'success');
                Session::flash('head', 'Item '.$actionName.' successfully');
                Session::flash('message', $this->title($this->modelName)." name '".$model->name."' ".$actionName.".");
                \DB::commit();
            } else {
                Session::flash('status', 'error');
                Session::flash('head', 'Item not '.$actionName.' successfully');
                Session::flash('message', $this->title($this->modelName)." name '".$model->name."' not ".$actionName.".");
            }    
        } catch (\Exception $exception) {
            \DB::rollback();
            $errorInfo = $exception->errorInfo;
            dd( $errorInfo );
            Session::flash('status', 'error');
            Session::flash('head', 'Item not '.$actionName.' successfully');
            Session::flash('message', $errorInfo);
        }

        return redirect()->route('bank.lists.edit', $model->getKey());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/bank/users/_delete.blade.php
{!! Form::open([
    'method'=>'DELETE', 
    'url' => route('bank.users.destroy', ['id'=>'']),
    'style' => 'display:none', 
    'id'    => 'delete-form']) !!}
{!! Form::close() !!}

@section('css')
    @parent
    <link href="{{ asset('css/sweetalert.css') }}" rel="stylesheet">
@show

@section('scripts')
    @parent
    <script src="{{asset('js/sweetalert.min.js')}}"></script>
    <script>
        $(document).ready(function(){
            $('.btn-delete').click(function () {
                const btn = $(this);
                swal({
                    title: "Are you sure?",
                    text: "Your will not be able to recover {{ $modelName }} '"+btn.data('title')+"'!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel this!",
                    closeOnConfirm: false,
                    closeOnCancel: false 
                }, function (isConfirm) {
                    if (isConfirm) {
                        $('.confirm').prop('disabled', true);
                        const fdelete = $('#delete-form');
                        fdelete.attr('action', fdelete.attr('action')+"/"+btn.data('id')).submit();
                    } else {
                        swal("Cancelled", "{{ $modelName }} data is safe :)", "error");
                    }
                });
            });
        });
    </script>
@show

resources/views/bank/users/_form.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">{{ $modelName }}</div>

    <div class="card-body">
        @include('layouts.flash-session')

        @if ($actionForm)
            @if( $model->exists )
                {!! Form::open([
                    'method' => 'PATCH',
                    'url' => route('bank.users.update', ['id'=>$model->getKey()]),
                ]) !!}
                {!! Form::hidden('id', $model->getKey()) !!}
            @else
            {!! Form::open([
                'method' => 'FETCH',
                'url' => route('bank.users.store'),
                ]) !!}
            @endif
        @endif

        <div class="form-group">
            <label>Type</label>
            {!! Form::select('type', $listType, $model->type, [
                    'class'         => 'form-control',
                    'id'            => 'type',
                    'disabled'      => (!$actionForm || $model->exists) ? true : false,
                    'placeholder'   => 'Choose Bank Type',
                ]) 
            !!}

            @if ($errors->has('type'))
                <small class="form-text text-danger">
                    {{ $errors->first('type') }}
                </small>
            @endif
        </div>

        <div class="form-group">
            <label>Bank Name</label>
            {!! Form::select('bank_id', $listBank, $model->bank_id, [
                    'class'         => 'form-control',
                    'disabled'      => (!$actionForm || $model->exists) ? true : false,
                    'placeholder'   => 'Choose Bank'
                ]) 
            !!}

            @if ($errors->has('bank_id'))
                <small class="form-text text-danger">
                    {{ $errors->first('bank_id') }}
                </small>
            @endif
        </div>

        <div class="form-group corpId">
            <label>Corp ID</label>
            {!! Form::text('corp_id', $model->corp_id, [
                    'class'          =>'form-control', 
                    'disabled'       => (!$actionForm || $model->exists) ? true : false,
                    'placeholder'    =>'Corp ID',
                ]) 
            !!}
            @if ($errors->has('corp_id'))
                <small class="form-text text-danger">
                    {{ $errors->first('corp_id') }}
                </small>
            @endif
        </div>

        <div class="form-group">
            <label>Username <span class="api">(Client ID)</span></label>
            {!! Form::text('username', $model->username, [
                    'class'          =>'form-control', 
                    'disabled'       => (!$actionForm || $model->exists) ? true : false,
                    'placeholder'    =>'Username',
                ]) 
            !!}
            @if ($errors->has('username'))
                <small class="form-text text-danger">
                    {{ $errors->first('username') }}
                </small>
            @endif
        </div>

        <div class="form-group">
            <label>Password <span class="api">(Client Secret)</span></label>
            {!! Form::password('password', [
                    'class'         =>'form-control', 
                    'disabled'      => (!$actionForm) ? true : false,
                    'placeholder'   => '************'
                ]) 
            !!}
            @if ($model->exists)
                <small class="form-text text-muted">
                    Leave empty to keep the same.
                </small>
            @endif
            @if ($errors->has('password'))
                <small class="form-text text-danger">
                    {{ $errors->first('password') }}
                </small>
            @endif
        </div>

        <div class="form-group">
            <label>Repeat Password</label>
            {!! Form::password('password_confirmation', [
                    'class'         =>'form-control', 
                    'disabled'      => (!$actionForm) ? true : false,
                    'placeholder'   => '************'
                ]) 
            !!}
            @if ($errors->has('password_confirmation'))
                <small class="form-text text-danger">
                    {{ $errors->first('password_confirmation') }}
                </small>
            @endif
        </div>

        <div class="form-group api">
            <label>Api Key</label>
            {!! Form::text('api_key', $model->api_key, [
                    'class'          =>'form-control api', 
                    'disabled'       => (!$actionForm || $model->exists) ? true : false,
                    'placeholder'    =>'y75qw-y78qw-ouqeq7-xxxx-xxxx',
                ]) 
            !!}
            @if ($errors->has('api_key'))
                <small class="form-text text-danger">
                    {{ $errors->first('api_key') }}
                </small>
            @endif
        </div>

        <div class="form-group api">
            <label>Api Secret Key</label>
            {!! Form::password('api_secret', [
                    'class'         =>'form-control api', 
                    'disabled'      => (!$actionForm) ? true : false,
                    'placeholder'   => '************'
                ]) 
            !!}
            @if ($model->exists)
                <small class="form-text text-muted">
                    Leave empty to keep the same.
                </small>
            @endif
            @if ($errors->has('api_secret'))
                <small class="form-text text-danger">
                    {{ $errors->first('api_secret') }}
                </small>
            @endif
        </div>

        <div class="form-group api">
            <label>Repeat Api Secret Key</label>
            {!! Form::password('api_secret_confirmation', [
                    'class'         =>'form-control api', 
                    'disabled'      => (!$actionForm) ? true : false,
                    'placeholder'   => '************'
                ]) 
            !!}
            @if ($errors->has('api_secret_confirmation'))
                <small class="form-text text-danger">
                    {{ $errors->first('api_secret_confirmation') }}
                </small>
            @endif
        </div>

        <div class="form-group">
            <label>Status</label>
            {!! Form::select('status', $listStatus, $model->status, [
                    'class'         => 'form-control',
                    'disabled'      => (!$actionForm) ? true : false,
                    'placeholder'   => 'Choose Status'
                ]) 
            !!}

            @if ($errors->has('status'))
                <small class="form-text text-danger">
                    {{ $errors->first('status') }}
                </small>
            @endif
        </div>

        <div class="col-sm-6 col-sm-offset-2">
            <a href="{{ route('bank.users.index') }}" class="btn btn-secondary btn-sm">
                <span class="fa fa-list"></span>
                Return to list
            </a>
            @if ($actionForm)
                {!! Form::submit($model->exists ? 'Save changes' : 'Save', ['class' => 'btn btn-success btn-sm']) !!}
            @else
                <a href="#" class="btn btn-danger btn-sm btn-delete" data-id='{{ $model->getKey() }}' data-title='{{ $model->username }}'>
                    <span class="fa fa-trash"></span>
                    Delete
                </a>
                <a href="{{ route('bank.users.edit', ['id'=>$model->getKey()]) }}" class="btn btn-warning btn-sm">
                    <span class="fa fa-pencil"></span>
                    Edit
                </a>
            @endif
        </div>

        {!! Form::close() !!}

        @if ($model->exists)
            @include('bank.users._delete')
        @endif
    </div>
</div>
@endsection

@section('scripts')
    <script>
        function toggle(a, b){
            if(a.val() == '1'){
                b.hide(500).prop('disabled', true);
            }else{
                b.show(500).prop('disabled', false);
            }
        }

        function toggleApi(a, b, c){
            if(a.val() == '2' && b.val() == '13'){
                c.show(500);
            }else{
                c.hide(500).prop('disabled', true);
            }
        }

        $(document).ready(function(){
            const a = $('#type'), b = $('.corpId'), c = $('select[name=bank_id]'), d = $('.api');

            toggle(a, b);
            toggleApi(a, c, d);

            $('#type').change(function () {
                toggle($(this), b);
                toggleApi(a, c, d);
            });

            $('select[name=bank_id]').change(function () {
                toggleApi(a, c, d);
            });
        });
    </script>
@endsection

resources/views/bank/users/index.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        {{ $modelName }}

        <a href="{{route('bank.users.create')}}" class="btn btn-default btn-xs float-right">
            <em class="fa fa-plus"></em>
            Create a new {{ $title }}
        </a>
    </div>

    <div class="card-body">
        @include('layouts.flash-session')

        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
                <th class="">Username / Register Date</th>
                <th class="">Type</th>
                <th class="">Bank Name</th>
                <th class="text-center">Status</th>
                <th class="text-center">Updated</th>
                <th class="text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
                @if ($models->count() == 0)
                    <tr>
                        <td colspan="6">No available {{ $title }}</td>
                    </tr>    
                @else
                    @foreach ($models as $model)
                    <tr>
                        <td>
                            <a href="{{ route('bank.users.show', $model->getKey()) }}">{{ $model->username }}</a>
                            <br/>
                            <small>Register at {{ $model->created_at->format('D, d-m-Y h:i') }}</small>
                        </td>
                        <td>
                            {{ $model->typeName }}
                        </td>
                        <td>
                            {{ $model->bank->name }}
                        </td>
                        <td class="text-center">
                            {{ $model->statusName }}
                        </td>
                        <td class="text-center">
                            <a href="#">{{ $model->updated_at->diffForHumans() }}</a>
                        </td>
                        <td>
                            <a href="{{route('bank.users.show', $model->getKey())}}" class="btn btn-primary btn-sm"><em class="fa fa-folder"></em> View </a>
                            <a href="{{route('bank.users.edit', $model->getKey())}}" class="btn btn-warning btn-sm"><em class="fa fa-pencil"></em> Edit </a>
                            <a href="#" class="btn btn-danger btn-sm btn-delete" data-id='{{ $model->getKey() }}' data-title='{{ $model->username }}'><em class="fa fa-trash"></em> Delete </a>
                        </td>
                    </tr>
                    @endforeach
                @endif
          </tbody>
        </table>
        {{ $models->onEachSide(1)->links() }}
    </div>
</div>
@include('bank.users._delete')
@endsection